import { chargerEnv } from './challenger/commun.mjs';
chargerEnv();
const cle = process.env.API_FOOTBALL_KEY!;
const j: any = await (await fetch(`https://v3.football.api-sports.io/fixtures?league=36&next=50`, { headers: { 'x-apisports-key': cle } })).json();
console.log('saison', j.response?.[0]?.league?.season, '·', (j.response ?? []).length, 'matchs à venir');
for (const f of j.response ?? []) console.log(' ', f.fixture.date.slice(0, 16), f.fixture.id, f.teams.home.name, '(' + f.teams.home.id + ')', '–', f.teams.away.name, '(' + f.teams.away.id + ')', '·', f.league.round);
const s: any = await (await fetch(`https://v3.football.api-sports.io/teams?search=ivoire`, { headers: { 'x-apisports-key': cle } })).json();
console.log('recherche « ivoire » :', (s.response ?? []).map((x: any) => x.team.name).join(', ') || 'rien');
const s2: any = await (await fetch(`https://v3.football.api-sports.io/teams?search=cameroun`, { headers: { 'x-apisports-key': cle } })).json();
console.log('recherche « cameroun » :', (s2.response ?? []).map((x: any) => x.team.name).join(', ') || 'rien');
