import { chargerEnv } from './challenger/commun.mjs';
chargerEnv();
const { lireSelectionDuJour } = await import('../src/lib/selection-du-jour.js');
const { matchsDuJour } = await import('../src/lib/grands-matchs-du-jour.js');
const s: any = await lireSelectionDuJour();
console.log(`SÉLECTION : ${s.matchs.length} match(s) · ${s.aujourdhui ? "aujourd'hui" : 'plus tard'}`);
for (const m of s.matchs) console.log('   ', m.kickoffISO.slice(0, 16), '·', m.championnat, '·', m.dom.name, '—', m.ext.name, '·', m.famille, m.fiabilite + '%');
const g: any = await matchsDuJour();
console.log(`MATCHS DU JOUR : ${g.matchs?.length ?? 0} carte(s) · ${g.aujourdhui ? "aujourd'hui" : 'plus tard'}`);
for (const m of (g.matchs ?? []).slice(0, 8)) console.log('   ', String(m.kickoffISO ?? m.date ?? '').slice(0, 16), '·', m.competition ?? m.championnat, '·', m.dom?.name, '—', m.ext?.name);
